// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkrhlervmodzmmugmqvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcmhsZXJ2bW9kem1tdWdtcXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzAxNjYsImV4cCI6MjA2NjYwNjE2Nn0.g_AWQ28INOeTkXyX2PTSjC2gXR4jPdl_ksHSnbG5XiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);